apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "20"
type: Opaque
data:
  accesskey: ay1yYXk=
  secretkey: ZmVlZGtyYXlzdGFycw==
