apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cwft-local
spec:
  templates:
  - name: git-checkout
    inputs:
      # parameters: 
      # - name: appDir
      # - name: branch
      #   value: "{{workflow.parameters.branch}}"
      #   default: main
      artifacts:
      - name: gitops-source
        path: /src/gitops
        git:
          repo: https://github.com/jarededwards/gitops
          revision: main
    container:
      image: golang:latest
      command: ["/bin/sh", "-c"]
      args: 
      - ls -la /src/gitops
    outputs:
      artifacts:
      - name: repo-source
        path: /src  
        
  - name: docker-build
    inputs:
      artifacts:
      - name: repo-source
        path: /src
      parameters: 
      - name: appDir
      - name: appName
    container:
      image: golang:latest
      command: ["/bin/sh", "-c"]
      args: 
      - ls -la /src
    # outputs:
    #   artifacts:
    #   - name: repo-source
    #     path: /src  