apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 0.20.1
    helm:
      values: |-
        server:
          extraArgs:
          - --auth-mode=client
        useDefaultArtifactRepo: true
        useStaticCredentials: true
        artifactRepository:
          archiveLogs: false
          s3:
            accessKeySecret:
              name: minio-creds
              key: accesskey
            secretKeySecret:
              name: minio-creds
              key: secretkey
            insecure: true
            bucket: argo-workflows-artifacts
            endpoint: http://minio.minio.svc.cluster.local:9000
            region: us-k3d-1
            useSDKCreds: false
            encryptionOptions:
              enableEncryption: false
    chart: argo-workflows
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "20"
type: Opaque
data:
  accesskey: ay1yYXk=
  secretkey: ZmVlZGtyYXlzdGFycw==
