apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cwft-local
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  templates:
  - name: git-checkout
    inputs:
      # parameters: 
      # - name: appDir
      # - name: branch
      #   value: "{{workflow.parameters.branch}}"
      #   default: main
      artifacts:
      - name: gitops-source
        path: /src/miller
        git:
          repo: https://github.com/jarededwards/miller
          revision: main
    container:
      image: golang:latest
      command: ["/bin/sh", "-c"]
      args: 
      - ls -la /src/miller
    outputs:
      artifacts:
      - name: repo-source
        path: /src
