apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-kubefirst
spec:
  # This will deploy 2 runners now
  replicas: 2
  template:
    spec:  
      repository: jarededwards/gitops
      image: summerwind/actions-runner-dind
      serviceAccountName: github-runner
      dockerdWithinRunnerContainer: true
      automountServiceAccountToken: true