apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.22.0
    helm:
      values: |-
        server:
          affinity: ""
          ha:
            enabled: true
          dev:
            enabled: true
            devRootToken: "k1_local_vault_token"
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks